name: fps_watcher
description: Android game telemetry monitor with Shizuku and Root backends.
publish_to: none
version: 1.3.0+130

environment:
  sdk: '>=3.4.0 <4.0.0'

platforms:
  android:

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: '#071018'
  adaptive_icon_foreground: assets/icon/app_icon_foreground.png
  min_sdk_android: 26
